version = "1.0"

[sink_group]
name = "default_infra"
windows = ["*"]

[[sink_group.sinks]]
connect = "file_json_sink"
name = "default_out"

[sink_group.sinks.params]
base = "./data/out_dat/"
file = "default.ndjson"
