version = "1.0"

[generator]
count = 1
speed = 1000
parallel = 1

[output]
connect = "syslog_udp_sink"

[output.params]
addr = "0.0.0.0"
port = 31600
protocol = "udp"

# [output.params]
# base = "data/in_dat"
# file = "gen.dat"

[logging]
level = ""
module_levels = []
output = ""
file_path = "./data/logs"

[presets]
