[[connectors]]
allow_override = ["endpoint", "api_path", "flush_secs", "timeout_secs"]
id = "victoriametrics_sink"
type = "victoriametrics"

[connectors.params]
api_path = "/api/v1/import/prometheus"
endpoint = "http://127.0.0.1:8428"
flush_secs = 1
timeout_secs = 5
