const OML_COMPLETION_TABLE = [
  {
    label: 'chars()',
    description: '直接创建常量值',
    example: 'chars(13)',
    insertText: 'chars(${chars})',
  },
  {
    label: 'digit()',
    description: '直接创建常量值',
    example: 'digit(13)',
    insertText: 'digit(${digit})',
  },
  {
    label: 'float()',
    description: '浮点常量值',
    example: 'float(3.14)',
    insertText: 'float(${float})',
  },
  {
    label: 'time()',
    description: '时间常量值',
    example: 'time(2026-01-19T12:34:56Z)',
    insertText: 'time(${time})',
  },
  {
    label: 'bool()',
    description: '布尔常量值',
    example: 'bool(true)',
    insertText: 'bool(${bool})',
  },
  {
    label: 'ip()',
    description: 'IP 常量值',
    example: 'ip(192.168.1.1)',
    insertText: 'ip(${ip})',
  },
  {
    label: 'read',
    description: '简单取值',
    example: 'read(simple_chars)',
    insertText: 'read(${Variable})',
  },
  {
    label: 'read(keys)',
    description: '通配符批量操作',
    example: 'a_name_fields = read(keys:[A*/name])',
    insertText: 'a_name_fields = read(${keys:[A*/name]})',
  },
  {
    label: 'read',
    description: '字段不存在时使用默认值',
    example: 'read(optional_field) { _ : chars(DEFAULT_VALUE) }',
    insertText: 'read(${field}) { _ : chars(DEFAULT) }',
  },
  {
    label: 'option:[]',
    description: '选择取值（按顺序尝试多个字段）',
    example: 'read(option:[select_one, select_two])',
    insertText: 'option:[${select_one}]',
  },
  {
    label: 'take',
    description: '破坏性读取并移除源字段',
    example: 'field_taken = take(source_field)',
    insertText: 'take(${source_field})',
  },
  {
    label: 'take',
    description: 'take失败使用默认值',
    example: 'field_taken_again = take(source_field) { _ : chars(already_taken) }',
    insertText: 'take(${source_field}) { _ : chars(DEFAULT) }',
  },
  {
    label: 'take()',
    description: '取所有字段',
    example: 'all_fields = take()',
    insertText: 'all_fields = take()',
  },
  {
    label: 'take(keys)',
    description: '通配符批量操作',
    example: 'path_fields = take(keys:[*/path])',
    insertText: 'path_fields = take(keys:[*/path])',
  },
  {
    label: 'Now::time()',
    description: '获取当前完整时间',
    example: 'current_time = Now::time()',
    insertText: 'current_time = Now::time()',
  },
  {
    label: 'Now::date()',
    description: '获取当前日期',
    example: 'current_date = Now::date()',
    insertText: 'Now::date()',
  },
  {
    label: 'Now::hour()',
    description: '获取当前小时',
    example: 'current_hour = Now::hour()',
    insertText: 'Now::hour()',
  },
  {
    label: 'match',
    description: '范围判断',
    example: 'num_range = match read(option:[num_range]) { in (digit(0), digit(1000)) => read(num_range) }',
    insertText: 'match read(option:[${num_range}]) { in (digit(0), digit(1000)) => read(num_range) }',
  },
  {
    label: 'match',
    description: '字段匹配',
    example: 'is_enabled : digit = match read(field) { bool(true) => digit(1) }',
    insertText: 'match read(${field}) {\n  _ => chars(defaule) \n}',
  },
  {
    label: 'match',
    description: '双字段组合匹配',
    example:
      'location : chars = match (read(city1), read(city2)) { (chars(beijing), chars(shanghai)) => chars(east_region) }',
    insertText:
      'location : chars = match (read(city1), read(city2)) { (chars(beijing), chars(shanghai)) => chars(east_region) }',
  },
  {
    label: 'match + !',
    description: '否定条件匹配',
    example: 'valid_status = match read(status) { !chars(error) => chars(ok) }',
    insertText: 'match read(status) { !chars(!{error}) => chars(ok) }',
  },
  {
    label: 'Time::to_ts_zone',
    description: '时间转换（时区）',
    example: 'timestamp_zone = pipe read(timestamp_zone) | Time::to_ts_zone(0, ms)',
    insertText: 'Time::to_ts_zone(${0}, ms)',
  },
  {
    label: 'Time::to_ts',
    description: '时间转换（秒级）',
    example: 'timestamp_s = pipe read(timestamp_zone) | Time::to_ts',
    insertText: 'Time::to_ts',
  },
  {
    label: 'Time::to_ts_ms',
    description: '时间转换（毫秒）',
    example: 'timestamp_ms = pipe @current_time | Time::to_ts_ms',
    insertText: 'Time::to_ts_ms',
  },
  {
    label: 'Time::to_ts_us',
    description: '时间转换（微秒）',
    example: 'timestamp_us = pipe @current_time | Time::to_ts_us',
    insertText: 'Time::to_ts_us',
  },
  {
    label: 'base64_decode',
    description: 'Base64 解码',
    example: 'base64_decoded = pipe read(base64) | base64_decode(Utf8)',
    insertText: 'base64_decode(${Utf8})',
  },
  {
    label: 'base64_encode',
    description: 'Base64 编码',
    example: 'base64_encoded = pipe read(base64) | base64_encode',
    insertText: 'base64_encode',
  },
  {
    label: 'html_escape',
    description: 'HTML 转义',
    example: 'html_escaped = pipe read(html) | html_escape',
    insertText: 'html_escape',
  },
  {
    label: 'html_unescape',
    description: 'HTML 反转义',
    example: 'html_unescaped = pipe read(html) | html_unescape',
    insertText: 'html_unescape',
  },
  {
    label: 'json_escape',
    description: 'JSON 转义',
    example: 'json_escaped = pipe read(json_escape) | json_escape',
    insertText: 'json_escape',
  },
  {
    label: 'json_unescape',
    description: 'JSON 反转义',
    example: 'json_unescaped = pipe @json_escaped | json_unescape',
    insertText: 'json_unescape',
  },
  {
    label: 'str_escape',
    description: '字符串转义',
    example: 'str_escaped = pipe read(str) | str_escape',
    insertText: 'str_escape',
  },
  {
    label: 'to_str',
    description: '转为字符串',
    example: 'to_str_result = pipe read(str) | to_str',
    insertText: 'to_str',
  },
  {
    label: 'to_json',
    description: '转为 JSON',
    example: 'array_json = pipe read(array_str) | to_json',
    insertText: 'to_json',
  },
  {
    label: 'ip4_to_int',
    description: 'IPv4 转整数',
    example: 'ip_to_int = pipe read(simple_ip) | ip4_to_int',
    insertText: 'ip4_to_int',
  },
  {
    label: 'nth',
    description: '数组取元素',
    example: 'array_first = pipe read(array_str) | nth(0)',
    insertText: 'nth(${0})',
  },
  {
    label: 'get',
    description: '对象嵌套取值',
    example: 'obj_nested = pipe read(obj) | nth(0) | get(one/two)',
    insertText: 'get(${one/two})',
  },
  {
    label: 'path(name)',
    description: '提取文件名',
    example: 'file_name = pipe read(path) | path(name)',
    insertText: 'path(name)',
  },
  {
    label: 'path(path)',
    description: '提取文件路径',
    example: 'file_path = pipe read(path) | path(path)',
    insertText: 'path(path)',
  },
  {
    label: 'starts_with',
    description: '字符串前缀检查',
    example: 'is_http = read(url) | starts_with(\"http://\")',
    insertText: 'starts_with(${\"prefix\"})',
  },
  {
    label: 'map_to',
    description: '映射到常量值',
    example: 'status = read(code) | map_to(200)',
    insertText: 'map_to(${value})',
  },
  {
    label: 'str_unescape',
    description: '字符串反转义',
    example: 'text = read(escaped) | str_unescape',
    insertText: 'str_unescape',
  },
  {
    label: 'extract_main_word',
    description: '提取主要单词',
    example: 'keyword = read(message) | extract_main_word',
    insertText: 'extract_main_word',
  },
  {
    label: 'extract_subject_object',
    description: '提取主客体结构',
    example: 'log_struct = read(message) | extract_subject_object',
    insertText: 'extract_subject_object',
  },
  {
    label: 'url(domain)',
    description: '提取 URL domain',
    example: 'url_domain = pipe read(url) | url(domain)',
    insertText: 'url(domain)',
  },
  {
    label: 'url(host)',
    description: '提取 URL host',
    example: 'url_host = pipe read(url) | url(host)',
    insertText: 'url(host)',
  },
  {
    label: 'url(uri)',
    description: '提取 URL uri',
    example: 'url_uri = pipe read(url) | url(uri)',
    insertText: 'url(uri)',
  },
  {
    label: 'url(path)',
    description: '提取 URL path',
    example: 'url_path = pipe read(url) | url(path)',
    insertText: 'url(path)',
  },
  {
    label: 'url(params)',
    description: '提取 URL params',
    example: 'url_params = pipe read(url) | url(params)',
    insertText: 'url(params)',
  },
  {
    label: 'skip_empty',
    description: '跳过空值',
    example: 'skip_empty_result = pipe read(empty_chars) | skip_empty',
    insertText: 'skip_empty',
  },
  {
    label: 'pipe',
    description: '流处理',
    example: 'pipe simple_transform = read(data) | to_json',
    insertText: 'pipe',
  },
  {
    label: 'fmt',
    description: '字符串格式化',
    example: 'splice = fmt("{one}:{two}|{three}:{four}", read(one), read(two), read(three), read(four))',
    insertText: 'fmt',
  },
  {
    label: 'object',
    description: '对象创建',
    example: 'extends = object { extend1, extend2 = read() }',
    insertText: 'object { }',
  },
  {
    label: 'collect',
    description: '数组收集',
    example: 'collected_ports : array = collect read(keys:[sport, dport, extra_port])',
    insertText: 'collect read(keys:[${sport}])',
  },
  {
    label: 'collect + 通配符',
    description: '通配符收集',
    example: 'wildcard_items : array = collect take(keys:[details[*]/process_name])',
    insertText: 'collect take(keys:[${details[*]/process_name}])',
  },
  // 以下为包含 | 字符的扩展数据
  {
    label: '|',
    description: '时间转换（时区）',
    example: 'timestamp_zone = pipe read(timestamp_zone) | Time::to_ts_zone(0, ms)',
    insertText: '| Time::to_ts_zone(${0}, ms)',
  },
  {
    label: '|',
    description: '时间转换（秒级）',
    example: 'timestamp_s = pipe read(timestamp_zone) | Time::to_ts',
    insertText: '| Time::to_ts',
  },
  {
    label: '|',
    description: '时间转换（毫秒）',
    example: 'timestamp_ms = pipe @current_time | Time::to_ts_ms',
    insertText: '| Time::to_ts_ms',
  },
  {
    label: '|',
    description: '时间转换（微秒）',
    example: 'timestamp_us = pipe @current_time | Time::to_ts_us',
    insertText: '| Time::to_ts_us',
  },
  {
    label: '|',
    description: 'Base64 解码',
    example: 'base64_decoded = pipe read(base64) | base64_decode(Utf8)',
    insertText: '| base64_decode(${Utf8})',
  },
  {
    label: '|',
    description: 'Base64 编码',
    example: 'base64_encoded = pipe read(base64) | base64_encode',
    insertText: '| base64_encode',
  },
  {
    label: '|',
    description: 'HTML 转义',
    example: 'html_escaped = pipe read(html) | html_escape',
    insertText: '| html_escape',
  },
  {
    label: '|',
    description: 'HTML 反转义',
    example: 'html_unescaped = pipe read(html) | html_unescape',
    insertText: '| html_unescape',
  },
  {
    label: '|',
    description: 'JSON 转义',
    example: 'json_escaped = pipe read(json_escape) | json_escape',
    insertText: '| json_escape',
  },
  {
    label: '|',
    description: 'JSON 反转义',
    example: 'json_unescaped = pipe @json_escaped | json_unescape',
    insertText: '| json_unescape',
  },
  {
    label: '|',
    description: '字符串转义',
    example: 'str_escaped = pipe read(str) | str_escape',
    insertText: '| str_escape',
  },
  {
    label: '|',
    description: '转为字符串',
    example: 'to_str_result = pipe read(str) | to_str',
    insertText: '| to_str',
  },
  {
    label: '|',
    description: '转为 JSON',
    example: 'array_json = pipe read(array_str) | to_json',
    insertText: '| to_json',
  },
  {
    label: '|',
    description: 'IPv4 转整数',
    example: 'ip_to_int = pipe read(simple_ip) | ip4_to_int',
    insertText: '| ip4_to_int',
  },
  {
    label: '|',
    description: '数组取元素',
    example: 'array_first = pipe read(array_str) | nth(0)',
    insertText: '| nth(${0})',
  },
  {
    label: '|',
    description: '对象嵌套取值',
    example: 'obj_nested = pipe read(obj) | nth(0) | get(one/two)',
    insertText: '| get(${one/two})',
  },
  {
    label: '|',
    description: '提取文件名',
    example: 'file_name = pipe read(path) | path(name)',
    insertText: '| path(name)',
  },
  {
    label: '|',
    description: '提取文件路径',
    example: 'file_path = pipe read(path) | path(path)',
    insertText: '| path(path)',
  },
  {
    label: '|',
    description: '字符串前缀检查',
    example: 'is_http = read(url) | starts_with(\"http://\")',
    insertText: '| starts_with(${\"prefix\"})',
  },
  {
    label: '|',
    description: '映射到常量值',
    example: 'status = read(code) | map_to(200)',
    insertText: '| map_to(${value})',
  },
  {
    label: '|',
    description: '字符串反转义',
    example: 'text = read(escaped) | str_unescape',
    insertText: '| str_unescape',
  },
  {
    label: '|',
    description: '提取主要单词',
    example: 'keyword = read(message) | extract_main_word',
    insertText: '| extract_main_word',
  },
  {
    label: '|',
    description: '提取主客体结构',
    example: 'log_struct = read(message) | extract_subject_object',
    insertText: '| extract_subject_object',
  },
  {
    label: '|',
    description: '提取 URL domain',
    example: 'url_domain = pipe read(url) | url(domain)',
    insertText: '| url(domain)',
  },
  {
    label: '|',
    description: '提取 URL host',
    example: 'url_host = pipe read(url) | url(host)',
    insertText: '| url(host)',
  },
  {
    label: '|',
    description: '提取 URL uri',
    example: 'url_uri = pipe read(url) | url(uri)',
    insertText: '| url(uri)',
  },
  {
    label: '|',
    description: '提取 URL path',
    example: 'url_path = pipe read(url) | url(path)',
    insertText: '| url(path)',
  },
  {
    label: '|',
    description: '提取 URL params',
    example: 'url_params = pipe read(url) | url(params)',
    insertText: '| url(params)',
  },
  {
    label: '|',
    description: '跳过空值',
    example: 'skip_empty_result = pipe read(empty_chars) | skip_empty',
    insertText: '| skip_empty',
  },
  {
    label: '|',
    description: '流处理',
    example: 'pipe simple_transform = read(data) | to_json',
    insertText: '| pipe',
  },
];

export default OML_COMPLETION_TABLE;
