const OML_COMPLETION_TABLE = [
  {
    label: 'chars()',
    description: 'Create constant value',
    example: 'chars(13)',
    insertText: 'chars(${chars})',
  },
  {
    label: 'digit()',
    description: 'Create constant value',
    example: 'digit(13)',
    insertText: 'digit(${digit})',
  },
  {
    label: 'float()',
    description: 'Create float constant value',
    example: 'float(3.14)',
    insertText: 'float(${float})',
  },
  {
    label: 'time()',
    description: 'Create time constant value',
    example: 'time(2026-01-19T12:34:56Z)',
    insertText: 'time(${time})',
  },
  {
    label: 'bool()',
    description: 'Create boolean constant value',
    example: 'bool(true)',
    insertText: 'bool(${bool})',
  },
  {
    label: 'ip()',
    description: 'Create IP constant value',
    example: 'ip(192.168.1.1)',
    insertText: 'ip(${ip})',
  },
  {
    label: 'read',
    description: 'Simple read',
    example: 'read(simple_chars)',
    insertText: 'read(${Variable})',
  },
  {
    label: 'read(keys)',
    description: 'Wildcard batch operation',
    example: 'a_name_fields = read(keys:[A*/name])',
    insertText: 'read(${keys:[A*/name]})',
  },
  {
    label: 'read',
    description: 'Use default when field missing',
    example: 'read(optional_field) { _ : chars(DEFAULT_VALUE) }',
    insertText: 'read(${field}) { _ : chars(DEFAULT) }',
  },
  {
    label: 'option:[]',
    description: 'Select values in order',
    example: 'read(option:[select_one, select_two])',
    insertText: 'option:[${select_one}]',
  },
  {
    label: 'take',
    description: 'Destructive read and remove source field',
    example: 'field_taken = take(source_field)',
    insertText: 'take(${source_field})',
  },
  {
    label: 'take',
    description: 'Use default when take fails',
    example: 'field_taken_again = take(source_field) { _ : chars(already_taken) }',
    insertText: 'take(${source_field}) { _ : chars(DEFAULT) }',
  },
  {
    label: 'take()',
    description: 'Take all fields',
    example: 'all_fields = take()',
    insertText: 'all_fields = take()',
  },
  {
    label: 'take(keys)',
    description: 'Wildcard batch operation',
    example: 'path_fields = take(keys:[*/path])',
    insertText: 'path_fields = take(keys:[*/path])',
  },
  {
    label: 'Now::time()',
    description: 'Get current full time',
    example: 'current_time = Now::time()',
    insertText: 'current_time = Now::time()',
  },
  {
    label: 'Now::date()',
    description: 'Get current date',
    example: 'current_date = Now::date()',
    insertText: 'Now::date()',
  },
  {
    label: 'Now::hour()',
    description: 'Get current hour',
    example: 'current_hour = Now::hour()',
    insertText: 'Now::hour()',
  },
  {
    label: 'match',
    description: 'Range match',
    example: 'num_range = match read(option:[num_range]) { in (digit(0), digit(1000)) => read(num_range) }',
    insertText: 'match read(option:[${num_range}]) { in (digit(0), digit(1000)) => read(num_range) }',
  },
  {
    label: 'match',
    description: 'Field match',
    example: 'is_enabled : digit = match read(enabled) { bool(true) => digit(1) }',
    insertText: 'match read(${field}) {\n  _ => chars(default)\n}',
  },
  {
    label: 'match',
    description: 'Two-field tuple match',
    example:
      'location : chars = match (read(city1), read(city2)) { (chars(beijing), chars(shanghai)) => chars(east_region) }',
    insertText:
      'location : chars = match (read(city1), read(city2)) { (chars(beijing), chars(shanghai)) => chars(east_region) }',
  },
  {
    label: 'match + !',
    description: 'Negation match',
    example: 'valid_status = match read(status) { !chars(error) => chars(ok) }',
    insertText: 'match read(status) { !chars(!{error}) => chars(ok) }',
  },
  {
    label: 'Time::to_ts_zone',
    description: 'Time conversion (timezone)',
    example: 'timestamp_zone = pipe read(timestamp_zone) | Time::to_ts_zone(0, ms)',
    insertText: 'Time::to_ts_zone(${0}, ms)',
  },
  {
    label: 'Time::to_ts',
    description: 'Time conversion (seconds)',
    example: 'timestamp_s = pipe read(timestamp_zone) | Time::to_ts',
    insertText: 'Time::to_ts',
  },
  {
    label: 'Time::to_ts_ms',
    description: 'Time conversion (milliseconds)',
    example: 'timestamp_ms = pipe @current_time | Time::to_ts_ms',
    insertText: 'Time::to_ts_ms',
  },
  {
    label: 'Time::to_ts_us',
    description: 'Time conversion (microseconds)',
    example: 'timestamp_us = pipe @current_time | Time::to_ts_us',
    insertText: 'Time::to_ts_us',
  },
  {
    label: 'base64_decode',
    description: 'Base64 decode',
    example: 'base64_decoded = pipe read(base64) | base64_decode(Utf8)',
    insertText: 'base64_decode(${Utf8})',
  },
  {
    label: 'base64_encode',
    description: 'Base64 encode',
    example: 'base64_encoded = pipe read(base64) | base64_encode',
    insertText: 'base64_encode',
  },
  {
    label: 'html_escape',
    description: 'HTML escape',
    example: 'html_escaped = pipe read(html) | html_escape',
    insertText: 'html_escape',
  },
  {
    label: 'html_unescape',
    description: 'HTML unescape',
    example: 'html_unescaped = pipe read(html) | html_unescape',
    insertText: 'html_unescape',
  },
  {
    label: 'json_escape',
    description: 'JSON escape',
    example: 'json_escaped = pipe read(json_escape) | json_escape',
    insertText: 'json_escape',
  },
  {
    label: 'json_unescape',
    description: 'JSON unescape',
    example: 'json_unescaped = pipe @json_escaped | json_unescape',
    insertText: 'json_unescape',
  },
  {
    label: 'str_escape',
    description: 'String escape',
    example: 'str_escaped = pipe read(str) | str_escape',
    insertText: 'str_escape',
  },
  {
    label: 'to_str',
    description: 'Convert to string',
    example: 'to_str_result = pipe read(str) | to_str',
    insertText: 'to_str',
  },
  {
    label: 'to_json',
    description: 'Convert to JSON',
    example: 'array_json = pipe read(array_str) | to_json',
    insertText: 'to_json',
  },
  {
    label: 'ip4_to_int',
    description: 'IPv4 to integer',
    example: 'ip_to_int = pipe read(simple_ip) | ip4_to_int',
    insertText: 'ip4_to_int',
  },
  {
    label: 'nth',
    description: 'Get array element',
    example: 'array_first = pipe read(array_str) | nth(0)',
    insertText: 'nth(${0})',
  },
  {
    label: 'get',
    description: 'Get nested object value',
    example: 'obj_nested = pipe read(obj) | nth(0) | get(one/two)',
    insertText: 'get(${one/two})',
  },
  {
    label: 'path(name)',
    description: 'Extract filename',
    example: 'file_name = pipe read(path) | path(name)',
    insertText: 'path(name)',
  },
  {
    label: 'path(path)',
    description: 'Extract file path',
    example: 'file_path = pipe read(path) | path(path)',
    insertText: 'path(path)',
  },
  {
    label: 'starts_with',
    description: 'String prefix check',
    example: 'is_http = read(url) | starts_with(\"http://\")',
    insertText: 'starts_with(${\"prefix\"})',
  },
  {
    label: 'map_to',
    description: 'Map to constant value',
    example: 'status = read(code) | map_to(200)',
    insertText: 'map_to(${value})',
  },
  {
    label: 'str_unescape',
    description: 'String unescape',
    example: 'text = read(escaped) | str_unescape',
    insertText: 'str_unescape',
  },
  {
    label: 'extract_main_word',
    description: 'Extract main word',
    example: 'keyword = read(message) | extract_main_word',
    insertText: 'extract_main_word',
  },
  {
    label: 'extract_subject_object',
    description: 'Extract subject-object structure',
    example: 'log_struct = read(message) | extract_subject_object',
    insertText: 'extract_subject_object',
  },
  {
    label: 'url(domain)',
    description: 'Extract URL domain',
    example: 'url_domain = pipe read(url) | url(domain)',
    insertText: 'url(domain)',
  },
  {
    label: 'url(host)',
    description: 'Extract URL host',
    example: 'url_host = pipe read(url) | url(host)',
    insertText: 'url(host)',
  },
  {
    label: 'url(uri)',
    description: 'Extract URL uri',
    example: 'url_uri = pipe read(url) | url(uri)',
    insertText: 'url(uri)',
  },
  {
    label: 'url(path)',
    description: 'Extract URL path',
    example: 'url_path = pipe read(url) | url(path)',
    insertText: 'url(path)',
  },
  {
    label: 'url(params)',
    description: 'Extract URL params',
    example: 'url_params = pipe read(url) | url(params)',
    insertText: 'url(params)',
  },
  {
    label: 'skip_empty',
    description: 'Skip empty values',
    example: 'skip_empty_result = pipe read(empty_chars) | skip_empty',
    insertText: 'skip_empty',
  },
  {
    label: 'pipe',
    description: 'Stream processing',
    example: 'pipe simple_transform = read(data) | to_json',
    insertText: 'pipe',
  },
  {
    label: 'fmt',
    description: 'String format',
    example: 'splice = fmt(\"{one}:{two}|{three}:{four}\", read(one), read(two), read(three), read(four))',
    insertText: 'fmt',
  },
  {
    label: 'object',
    description: 'Create object',
    example: 'extends = object { extend1, extend2 = read() }',
    insertText: 'object { }',
  },
  {
    label: 'collect',
    description: 'Collect array',
    example: 'collected_ports : array = collect read(keys:[sport, dport, extra_port])',
    insertText: 'collect read(keys:[${sport}])',
  },
  {
    label: 'collect + 通配符',
    description: 'Collect with wildcard',
    example: 'wildcard_items : array = collect take(keys:[details[*]/process_name])',
    insertText: 'collect take(keys:[${details[*]/process_name}])',
  },
  {
    label: '|',
    description: 'Time conversion (timezone)',
    example: 'timestamp_zone = pipe read(timestamp_zone) | Time::to_ts_zone(0, ms)',
    insertText: '| Time::to_ts_zone(${0}, ms)',
  },
  {
    label: '|',
    description: 'Time conversion (seconds)',
    example: 'timestamp_s = pipe read(timestamp_zone) | Time::to_ts',
    insertText: '| Time::to_ts',
  },
  {
    label: '|',
    description: 'Time conversion (milliseconds)',
    example: 'timestamp_ms = pipe @current_time | Time::to_ts_ms',
    insertText: '| Time::to_ts_ms',
  },
  {
    label: '|',
    description: 'Time conversion (microseconds)',
    example: 'timestamp_us = pipe @current_time | Time::to_ts_us',
    insertText: '| Time::to_ts_us',
  },
  {
    label: '|',
    description: 'Base64 decode',
    example: 'base64_decoded = pipe read(base64) | base64_decode(Utf8)',
    insertText: '| base64_decode(${Utf8})',
  },
  {
    label: '|',
    description: 'Base64 encode',
    example: 'base64_encoded = pipe read(base64) | base64_encode',
    insertText: '| base64_encode',
  },
  {
    label: '|',
    description: 'HTML escape',
    example: 'html_escaped = pipe read(html) | html_escape',
    insertText: '| html_escape',
  },
  {
    label: '|',
    description: 'HTML unescape',
    example: 'html_unescaped = pipe read(html) | html_unescape',
    insertText: '| html_unescape',
  },
  {
    label: '|',
    description: 'JSON escape',
    example: 'json_escaped = pipe read(json_escape) | json_escape',
    insertText: '| json_escape',
  },
  {
    label: '|',
    description: 'JSON unescape',
    example: 'json_unescaped = pipe @json_escaped | json_unescape',
    insertText: '| json_unescape',
  },
  {
    label: '|',
    description: 'String escape',
    example: 'str_escaped = pipe read(str) | str_escape',
    insertText: '| str_escape',
  },
  {
    label: '|',
    description: 'Convert to string',
    example: 'to_str_result = pipe read(str) | to_str',
    insertText: '| to_str',
  },
  {
    label: '|',
    description: 'Convert to JSON',
    example: 'array_json = pipe read(array_str) | to_json',
    insertText: '| to_json',
  },
  {
    label: '|',
    description: 'IPv4 to integer',
    example: 'ip_to_int = pipe read(simple_ip) | ip4_to_int',
    insertText: '| ip4_to_int',
  },
  {
    label: '|',
    description: 'Get array element',
    example: 'array_first = pipe read(array_str) | nth(0)',
    insertText: '| nth(${0})',
  },
  {
    label: '|',
    description: 'Get nested object value',
    example: 'obj_nested = pipe read(obj) | nth(0) | get(one/two)',
    insertText: '| get(${one/two})',
  },
  {
    label: '|',
    description: 'Extract filename',
    example: 'file_name = pipe read(path) | path(name)',
    insertText: '| path(name)',
  },
  {
    label: '|',
    description: 'Extract file path',
    example: 'file_path = pipe read(path) | path(path)',
    insertText: '| path(path)',
  },
  {
    label: '|',
    description: 'String prefix check',
    example: 'is_http = read(url) | starts_with(\"http://\")',
    insertText: '| starts_with(${\"prefix\"})',
  },
  {
    label: '|',
    description: 'Map to constant value',
    example: 'status = read(code) | map_to(200)',
    insertText: '| map_to(${value})',
  },
  {
    label: '|',
    description: 'String unescape',
    example: 'text = read(escaped) | str_unescape',
    insertText: '| str_unescape',
  },
  {
    label: '|',
    description: 'Extract main word',
    example: 'keyword = read(message) | extract_main_word',
    insertText: '| extract_main_word',
  },
  {
    label: '|',
    description: 'Extract subject-object structure',
    example: 'log_struct = read(message) | extract_subject_object',
    insertText: '| extract_subject_object',
  },
  {
    label: '|',
    description: 'Extract URL domain',
    example: 'url_domain = pipe read(url) | url(domain)',
    insertText: '| url(domain)',
  },
  {
    label: '|',
    description: 'Extract URL host',
    example: 'url_host = pipe read(url) | url(host)',
    insertText: '| url(host)',
  },
  {
    label: '|',
    description: 'Extract URL uri',
    example: 'url_uri = pipe read(url) | url(uri)',
    insertText: '| url(uri)',
  },
  {
    label: '|',
    description: 'Extract URL path',
    example: 'url_path = pipe read(url) | url(path)',
    insertText: '| url(path)',
  },
  {
    label: '|',
    description: 'Extract URL params',
    example: 'url_params = pipe read(url) | url(params)',
    insertText: '| url(params)',
  },
  {
    label: '|',
    description: 'Skip empty values',
    example: 'skip_empty_result = pipe read(empty_chars) | skip_empty',
    insertText: '| skip_empty',
  },
  {
    label: '|',
    description: 'Stream processing',
    example: 'pipe simple_transform = read(data) | to_json',
    insertText: '| pipe',
  },
];

export default OML_COMPLETION_TABLE;
