const WPL_COMPLETION_TABLE = [
  {
    label: 'peek_symbol',
    kind: 'type',
    description: 'Preview match without consuming input',
    example: 'peek_symbol(peek_symbol)',
    insertText: 'peek_symbol(${peek_symbol})',
  },
  {
    label: 'symbol',
    kind: 'type',
    description: 'Exact match for specified string',
    example: 'symbol(symbol)',
    insertText: 'symbol(${symbol})',
  },
  {
    label: 'bool',
    kind: 'type',
    description: 'Boolean value, matches true/false',
    example: 'true',
    insertText: 'bool',
  },
  {
    label: 'auto',
    kind: 'type',
    description: 'Auto type inference',
    example: 'auto',
    insertText: 'auto',
  },
  {
    label: 'chars',
    kind: 'type',
    description: 'String, quoted or bare',
    example: '"hello" / hello',
    insertText: 'chars',
  },
  {
    label: 'array',
    kind: 'type',
    description: 'The array type can be followed by the types of the fields within it.',
    example: '["a", "b", "c"]',
    insertText: 'array/chars',
  },
  {
    label: 'digit',
    kind: 'type',
    description: 'Integer',
    example: '123 / -456',
    insertText: 'digit',
  },
  {
    label: 'float',
    kind: 'type',
    description: 'Float',
    example: '3.14 / -0.5',
    insertText: 'float',
  },
  {
    label: 'time',
    kind: 'type',
    description: 'RFC3339/ISO 8601 time',
    example: '2026-01-19T12:34:56Z / 2022-03-21T12:34:56+00:00',
    insertText: 'time',
  },
  {
    label: 'time_3339',
    kind: 'type',
    description: 'RFC3339/ISO 8601 time',
    example: '2026-01-19T12:34:56Z / 2022-03-21T12:34:56+00:00',
    insertText: 'time_3339',
  },
  {
    label: 'time/rfc3339',
    kind: 'type',
    description: 'RFC3339 time',
    example: '2026-01-19T12:34:56Z',
    insertText: 'time/rfc3339',
  },
  {
    label: 'time_iso',
    kind: 'type',
    description: 'ISO time',
    example: '2026-01-19T12:34:56Z / 2022-03-21T12:34:56+00:00',
    insertText: 'time_iso',
  },
  {
    label: 'time_2822',
    kind: 'type',
    description: 'RFC2822 email time format',
    example: 'Mon, 07 Jul 2025 09:20:32 +0000',
    insertText: 'time_2822',
  },
  {
    label: 'time/rfc2822',
    kind: 'type',
    description: 'RFC2822 time format',
    example: 'Mon, 07 Jul 2025 09:20:32 +0000',
    insertText: 'time/rfc2822',
  },
  {
    label: 'time/clf',
    kind: 'type',
    description: 'Common Log Format time',
    example: '[06/Aug/2019:12:12:19 +0800]',
    insertText: 'time/clf',
  },
  {
    label: 'time/apache',
    kind: 'type',
    description: 'Apache time format',
    example: '[06/Aug/2019:12:12:19 +0800]',
    insertText: 'time/apache',
  },
  {
    label: 'time/httpd',
    kind: 'type',
    description: 'HTTPD time format',
    example: '[06/Aug/2019:12:12:19 +0800]',
    insertText: 'time/httpd',
  },
  {
    label: 'time/nginx',
    kind: 'type',
    description: 'Nginx time format',
    example: '[06/Aug/2019:12:12:19 +0800]',
    insertText: 'time/nginx',
  },
  {
    label: 'time_timestamp',
    kind: 'type',
    description: 'Unix seconds timestamp',
    example: '1647849600',
    insertText: 'time_timestamp',
  },
  {
    label: 'time/timestamp',
    kind: 'type',
    description: 'Timestamp',
    example: '1647849600',
    insertText: 'time/timestamp',
  },
  {
    label: 'ip',
    kind: 'type',
    description: 'IPv4/IPv6 address',
    example: '192.168.1.100 / ::1',
    insertText: 'ip',
  },
  {
    label: 'ip_net',
    kind: 'type',
    description: 'CIDR network',
    example: '192.168.0.0/24',
    insertText: 'ip_net',
  },
  {
    label: 'port',
    kind: 'type',
    description: 'Port number (1-65535)',
    example: '8080',
    insertText: 'port',
  },
  {
    label: 'kvarr',
    kind: 'type',
    description: 'Key-value pair key=value',
    example: 'key="value"',
    insertText: 'kvarr(${chars@name})',
  },
  {
    label: 'kv',
    kind: 'type',
    description: 'Key-value',
    example: 'key=value',
    insertText: 'kv',
  },
  {
    label: 'json',
    kind: 'type',
    description: 'JSON object',
    example: '{"strict":true}',
    insertText: 'json(${chars@field})',
  },
  {
    label: 'exact_json',
    kind: 'type',
    description: 'Strict JSON',
    example: '{"strict":true}',
    insertText: 'exact_json',
  },
  {
    label: 'http/request',
    kind: 'type',
    description: 'HTTP request line',
    example: '"GET /api/users HTTP/1.1"',
    insertText: 'http/request',
  },
  {
    label: 'http/status',
    kind: 'type',
    description: 'HTTP status code',
    example: '200',
    insertText: 'http/status',
  },
  {
    label: 'http/agent',
    kind: 'type',
    description: 'User-Agent',
    example: '"Mozilla/5.0"',
    insertText: 'http/agent',
  },
  {
    label: 'http/user_agent',
    kind: 'type',
    description: 'User-Agent',
    example: '"Mozilla/5.0"',
    insertText: 'http/user_agent',
  },
  {
    label: 'http/method',
    kind: 'type',
    description: 'HTTP method',
    example: '"POST"',
    insertText: 'http/method',
  },
  {
    label: 'domain',
    kind: 'type',
    description: 'Domain',
    example: 'example.com',
    insertText: 'domain',
  },
  {
    label: 'email',
    kind: 'type',
    description: 'Email address',
    example: 'user@example.com',
    insertText: 'email',
  },
  {
    label: 'hex',
    kind: 'type',
    description: 'Hex string',
    example: '0x1A2B / 1A2B',
    insertText: 'hex',
  },
  {
    label: 'base64',
    kind: 'type',
    description: 'Base64 string',
    example: 'YmFzZTY0ZGF0YQ==',
    insertText: 'base64',
  },
  {
    label: 'url',
    kind: 'type',
    description: 'URL',
    example: 'https://example.com/path',
    insertText: 'url',
  },
  {
    label: 'proto_text',
    kind: 'type',
    description: 'Protocol text',
    example: 'message Example { string name = 1; }',
    insertText: 'proto_text',
  },
  {
    label: 'proto/text',
    kind: 'type',
    description: 'Protocol text',
    example: 'message Example { string name = 1; }',
    insertText: 'proto/text',
  },
  {
    label: 'obj',
    kind: 'type',
    description: 'Object',
    example: '{"key":"value"}',
    insertText: 'obj',
  },
  {
    label: 'sn',
    kind: 'type',
    description: 'Alphanumeric serial number',
    example: 'ABC123XYZ',
    insertText: 'sn',
  },
  {
    label: 'id_card',
    kind: 'type',
    description: 'ID card number',
    example: '110101199003071234',
    insertText: 'id_card',
  },
  {
    label: 'mobile_phone',
    kind: 'type',
    description: 'Mobile phone number',
    example: '13800138000',
    insertText: 'mobile_phone',
  },
  {
    label: '_',
    kind: 'type',
    description: 'Ignore this field',
    example: 'Ignore this field',
    insertText: '_',
  },
  {
    label: 'decode/base64',
    kind: 'function',
    description: 'Base64 decode whole line',
    example: 'aGVsbG8=',
    insertText: 'decode/base64',
  },
  {
    label: 'decode/hex',
    kind: 'function',
    description: 'Hex decode whole line',
    example: 'hello',
    insertText: 'decode/hex',
  },
  {
    label: 'strip/bom',
    kind: 'function',
    description: 'Remove BOM (byte order mark)',
    example: '|strip/bom|',
    insertText: 'strip/bom',
  },
  {
    label: 'unquote/unescape',
    kind: 'function',
    description: 'Remove quotes and unescape',
    example: '"FW\\|action=DROP\\n\\tmsg"',
    insertText: 'unquote/unescape',
  },
  {
    label: 'plg_pipe',
    kind: 'function',
    description: 'Custom preprocessor extension',
    example: '|plg_pipe/dayu|',
    insertText: 'plg_pipe/${name}',
  },
  {
    label: 'take',
    kind: 'function',
    description: 'Select specified field as active',
    example: '|take(name)|',
    insertText: 'take(${name})',
  },
  {
    label: 'last',
    kind: 'function',
    description: 'Select last field as active',
    example: '|last()|',
    insertText: 'last()',
  },
  {
    label: 'f_has',
    kind: 'function',
    description: 'Check field exists',
    example: '|f_has(status)|',
    insertText: 'f_has(${name})',
  },
  {
    label: 'f_chars_has',
    kind: 'function',
    description: 'Check field equals string',
    example: '|f_chars_has(status, success)|',
    insertText: 'f_chars_has(${name}, ${val})',
  },
  {
    label: 'f_chars_not_has',
    kind: 'function',
    description: 'Check field not equal string',
    example: '|f_chars_not_has(level, error)|',
    insertText: 'f_chars_not_has(${name}, ${val})',
  },
  {
    label: 'f_chars_in',
    kind: 'function',
    description: 'Check field in string list',
    example: '|f_chars_in(method, [GET, POST])|',
    insertText: 'f_chars_in(${name}, [...])',
  },
  {
    label: 'f_digit_has',
    kind: 'function',
    description: 'Check field equals number',
    example: '|f_digit_has(code, 200)|',
    insertText: 'f_digit_has(${name}, ${num})',
  },
  {
    label: 'f_digit_in',
    kind: 'function',
    description: 'Check field in number list',
    example: '|f_digit_in(status, [200, 201])|',
    insertText: 'f_digit_in(${name}, [...])',
  },
  {
    label: 'f_ip_in',
    kind: 'function',
    description: 'Check IP in list',
    example: '|f_ip_in(client_ip, [127.0.0.1])|',
    insertText: 'f_ip_in(${name}, [...])',
  },
  {
    label: 'has',
    kind: 'function',
    description: 'Check active field exists',
    example: '|take(name)| has()|',
    insertText: 'has()',
  },
  {
    label: 'chars_has',
    kind: 'function',
    description: 'Check active field equals string',
    example: '|take(status)| chars_has(success)|',
    insertText: 'chars_has(${val})',
  },
  {
    label: 'chars_not_has',
    kind: 'function',
    description: 'Check active field not equal string',
    example: '|take(level)| chars_not_has(error)|',
    insertText: 'chars_not_has(${val})',
  },
  {
    label: 'chars_in',
    kind: 'function',
    description: 'Check active field in string list',
    example: '|take(method)| chars_in([GET, POST])|',
    insertText: 'chars_in([${...}])',
  },
  {
    label: 'starts_with',
    kind: 'function',
    description: 'Check active field starts with prefix',
    example: '|take(url)| starts_with(\"http\")|',
    insertText: 'starts_with(\"${prefix}\")',
  },
  {
    label: 'regex_match',
    kind: 'function',
    description: 'Regex match active field',
    example: '|take(message)| regex_match(\"error\")|',
    insertText: 'regex_match(\"${pattern}\")',
  },
  {
    label: 'digit_has',
    kind: 'function',
    description: 'Check active field equals number',
    example: '|take(code)| digit_has(200)|',
    insertText: 'digit_has(${num})',
  },
  {
    label: 'digit_in',
    kind: 'function',
    description: 'Check active field in number list',
    example: '|take(status)| digit_in([200, 201])|',
    insertText: 'digit_in([${...}])',
  },
  {
    label: 'digit_range',
    kind: 'function',
    description: 'Check active field in number range',
    example: '|take(status)| digit_range(200, 299)|',
    insertText: 'digit_range(${min}, ${max})',
  },
  {
    label: 'ip_in',
    kind: 'function',
    description: 'Check active IP in list',
    example: '|take(client_ip)| ip_in([127.0.0.1])|',
    insertText: 'ip_in([${...}])',
  },
  {
    label: 'json_unescape',
    kind: 'function',
    description: 'JSON unescape',
    example: '|take(message)| json_unescape()|',
    insertText: 'json_unescape()',
  },
  {
    label: 'base64_decode',
    kind: 'function',
    description: 'Base64 decode',
    example: '|take(payload)| base64_decode()|',
    insertText: 'base64_decode()',
  },
  {
    label: 'chars_replace',
    kind: 'function',
    description: 'Replace characters',
    example: '|take(message)| chars_replace(error, ok)|',
    insertText: 'chars_replace(${from}, ${to})',
  },
  {
    label: 'not',
    kind: 'function',
    description: 'Negate function result',
    example: '|not(chars_has(error))|',
    insertText: 'not(${fun_call})',
  },
];

export default WPL_COMPLETION_TABLE;
