const WPL_COMPLETION_TABLE = [
  {
    label: 'peek_symbol',
    kind: 'type',
    description: '预读匹配但不消费输入',
    example: 'peek_symbol(peek_symbol)',
    insertText: 'peek_symbol(${peek_symbol})',
  },
  {
    label: 'symbol',
    kind: 'type',
    description: '精确匹配指定字符串',
    example: 'symbol(symbol)',
    insertText: 'symbol(${symbol})',
  },
  {
    label: 'bool',
    kind: 'type',
    description: '布尔值，匹配 true/false',
    example: 'true',
    insertText: 'bool',
  },
  {
    label: 'auto',
    kind: 'type',
    description: '自动类型推断',
    example: 'auto',
    insertText: 'auto',
  },
  {
    label: 'chars',
    kind: 'type',
    description: '字符串，支持引号或裸字符串',
    example: '"hello" / hello',
    insertText: 'chars',
  },
  {
    label: 'array',
    kind: 'type',
    description: '数组类型后面可以接里面字段的类型',
    example: '["a", "b", "c"]',
    insertText: 'array/chars',
  },
  {
    label: 'digit',
    kind: 'type',
    description: '整数',
    example: '123 / -456',
    insertText: 'digit',
  },
  {
    label: 'float',
    kind: 'type',
    description: '浮点数',
    example: '3.14 / -0.5',
    insertText: 'float',
  },
  {
    label: 'time',
    kind: 'type',
    description: 'RFC3339/ISO 8601 时间',
    example: '2026-01-19T12:34:56Z / 2022-03-21T12:34:56+00:00',
    insertText: 'time',
  },
  {
    label: 'time_iso',
    kind: 'type',
    description: 'ISO 时间',
    example: '2026-01-19T12:34:56Z / 2022-03-21T12:34:56+00:00',
    insertText: 'time_iso',
  },
  {
    label: 'time_3339',
    kind: 'type',
    description: 'RFC3339/ISO 8601 时间',
    example: '2026-01-19T12:34:56Z / 2022-03-21T12:34:56+00:00',
    insertText: 'time_3339',
  },
  {
    label: 'time/rfc3339',
    kind: 'type',
    description: 'RFC3339 时间',
    example: '2026-01-19T12:34:56Z',
    insertText: 'time/rfc3339',
  },
  {
    label: 'time_2822',
    kind: 'type',
    description: 'RFC2822 邮件时间格式',
    example: 'Mon, 07 Jul 2025 09:20:32 +0000',
    insertText: 'time_2822',
  },
  {
    label: 'time/rfc2822',
    kind: 'type',
    description: 'RFC2822 时间格式',
    example: 'Mon, 07 Jul 2025 09:20:32 +0000',
    insertText: 'time/rfc2822',
  },
  {
    label: 'time/clf',
    kind: 'type',
    description: 'Common Log Format 时间',
    example: '[06/Aug/2019:12:12:19 +0800]',
    insertText: 'time/clf',
  },
  {
    label: 'time/apache',
    kind: 'type',
    description: 'Apache 时间格式',
    example: '[06/Aug/2019:12:12:19 +0800]',
    insertText: 'time/apache',
  },
  {
    label: 'time/httpd',
    kind: 'type',
    description: 'HTTPD 时间格式',
    example: '[06/Aug/2019:12:12:19 +0800]',
    insertText: 'time/httpd',
  },
  {
    label: 'time/nginx',
    kind: 'type',
    description: 'Nginx 时间格式',
    example: '[06/Aug/2019:12:12:19 +0800]',
    insertText: 'time/nginx',
  },
  {
    label: 'time_timestamp',
    kind: 'type',
    description: 'Unix 秒级时间戳',
    example: '1647849600',
    insertText: 'time_timestamp',
  },
  {
    label: 'time/timestamp',
    kind: 'type',
    description: '时间戳',
    example: '1647849600',
    insertText: 'time/timestamp',
  },
  {
    label: 'ip',
    kind: 'type',
    description: 'IPv4/IPv6 地址',
    example: '192.168.1.100 / ::1',
    insertText: 'ip',
  },
  {
    label: 'ip_net',
    kind: 'type',
    description: 'CIDR 网段',
    example: '192.168.0.0/24',
    insertText: 'ip_net',
  },
  {
    label: 'port',
    kind: 'type',
    description: '端口号（1-65535）',
    example: '8080',
    insertText: 'port',
  },
  {
    label: 'kvarr',
    kind: 'type',
    description: '键值对 key=value',
    example: 'key="value"',
    insertText: 'kvarr(${chars@name})',
  },
  {
    label: 'kv',
    kind: 'type',
    description: '键值对',
    example: 'key=value',
    insertText: 'kv',
  },
  {
    label: 'json',
    kind: 'type',
    description: 'JSON 对象',
    example: '{"strict":true}',
    insertText: 'json(${chars@field})',
  },
  {
    label: 'exact_json',
    kind: 'type',
    description: '严格 JSON',
    example: '{"strict":true}',
    insertText: 'exact_json',
  },
  {
    label: 'http/request',
    kind: 'type',
    description: 'HTTP 请求行',
    example: '"GET /api/users HTTP/1.1"',
    insertText: 'http/request',
  },
  {
    label: 'http/status',
    kind: 'type',
    description: 'HTTP 状态码',
    example: '200',
    insertText: 'http/status',
  },
  {
    label: 'http/agent',
    kind: 'type',
    description: 'User-Agent',
    example: '"Mozilla/5.0"',
    insertText: 'http/agent',
  },
  {
    label: 'http/user_agent',
    kind: 'type',
    description: 'User-Agent',
    example: '"Mozilla/5.0"',
    insertText: 'http/user_agent',
  },
  {
    label: 'http/method',
    kind: 'type',
    description: 'HTTP 方法',
    example: '"POST"',
    insertText: 'http/method',
  },
  {
    label: 'domain',
    kind: 'type',
    description: '域名',
    example: 'example.com',
    insertText: 'domain',
  },
  {
    label: 'email',
    kind: 'type',
    description: '邮箱地址',
    example: 'user@example.com',
    insertText: 'email',
  },
  {
    label: 'hex',
    kind: 'type',
    description: '十六进制字符串',
    example: '0x1A2B / 1A2B',
    insertText: 'hex',
  },
  {
    label: 'base64',
    kind: 'type',
    description: 'Base64 编码字符串',
    example: 'YmFzZTY0ZGF0YQ==',
    insertText: 'base64',
  },
  {
    label: 'url',
    kind: 'type',
    description: 'URL',
    example: 'https://example.com/path',
    insertText: 'url',
  },
  {
    label: 'proto_text',
    kind: 'type',
    description: '协议文本',
    example: 'message Example { string name = 1; }',
    insertText: 'proto_text',
  },
  {
    label: 'proto/text',
    kind: 'type',
    description: '协议文本',
    example: 'message Example { string name = 1; }',
    insertText: 'proto/text',
  },
  {
    label: 'obj',
    kind: 'type',
    description: '对象',
    example: '{"key":"value"}',
    insertText: 'obj',
  },
  {
    label: 'sn',
    kind: 'type',
    description: '字母数字序列号',
    example: 'ABC123XYZ',
    insertText: 'sn',
  },
  {
    label: 'id_card',
    kind: 'type',
    description: '身份证号',
    example: '110101199003071234',
    insertText: 'id_card',
  },
  {
    label: 'mobile_phone',
    kind: 'type',
    description: '手机号',
    example: '13800138000',
    insertText: 'mobile_phone',
  },
  {
    label: '_',
    kind: 'type',
    description: '忽略该字段',
    example: '忽略该字段',
    insertText: '_',
  },
  {
    label: 'decode/base64',
    kind: 'function',
    description: '对整行 Base64 解码',
    example: 'aGVsbG8=',
    insertText: 'decode/base64',
  },
  {
    label: 'decode/hex',
    kind: 'function',
    description: '对整行十六进制解码',
    example: 'hello',
    insertText: 'decode/hex',
  },
  {
    label: 'strip/bom',
    kind: 'function',
    description: '移除 BOM（字节顺序标记）',
    example: '|strip/bom|',
    insertText: 'strip/bom',
  },
  {
    label: 'unquote/unescape',
    kind: 'function',
    description: '移除引号并还原转义',
    example: '"FW\\|action=DROP\\n\\tmsg"',
    insertText: 'unquote/unescape',
  },
  {
    label: 'plg_pipe',
    kind: 'function',
    description: '自定义预处理扩展',
    example: '|plg_pipe/dayu|',
    insertText: 'plg_pipe/${name}',
  },
  {
    label: 'take',
    kind: 'function',
    description: '选择指定字段为活跃字段',
    example: '|take(name)|',
    insertText: 'take(${name})',
  },
  {
    label: 'last',
    kind: 'function',
    description: '选择最后一个字段为活跃字段',
    example: '|last()|',
    insertText: 'last()',
  },
  {
    label: 'f_has',
    kind: 'function',
    description: '检查字段是否存在',
    example: '|f_has(status)|',
    insertText: 'f_has(${name})',
  },
  {
    label: 'f_chars_has',
    kind: 'function',
    description: '检查字段值等于字符串',
    example: '|f_chars_has(status, success)|',
    insertText: 'f_chars_has(${name}, ${val})',
  },
  {
    label: 'f_chars_not_has',
    kind: 'function',
    description: '检查字段值不等于字符串',
    example: '|f_chars_not_has(level, error)|',
    insertText: 'f_chars_not_has(${name}, ${val})',
  },
  {
    label: 'f_chars_in',
    kind: 'function',
    description: '检查字段值在字符串列表',
    example: '|f_chars_in(method, [GET, POST])|',
    insertText: 'f_chars_in(${name}, [...])',
  },
  {
    label: 'f_digit_has',
    kind: 'function',
    description: '检查字段值等于数字',
    example: '|f_digit_has(code, 200)|',
    insertText: 'f_digit_has(${name}, ${num})',
  },
  {
    label: 'f_digit_in',
    kind: 'function',
    description: '检查字段值在数字列表',
    example: '|f_digit_in(status, [200, 201])|',
    insertText: 'f_digit_in(${name}, [...])',
  },
  {
    label: 'f_ip_in',
    kind: 'function',
    description: '检查 IP 在列表',
    example: '|f_ip_in(client_ip, [127.0.0.1])|',
    insertText: 'f_ip_in(${name}, [...])',
  },
  {
    label: 'has',
    kind: 'function',
    description: '检查活跃字段存在',
    example: '|take(name)| has()|',
    insertText: 'has()',
  },
  {
    label: 'chars_has',
    kind: 'function',
    description: '检查活跃字段等于字符串',
    example: '|take(status)| chars_has(success)|',
    insertText: 'chars_has(${val})',
  },
  {
    label: 'chars_not_has',
    kind: 'function',
    description: '检查活跃字段不等于字符串',
    example: '|take(level)| chars_not_has(error)|',
    insertText: 'chars_not_has(${val})',
  },
  {
    label: 'chars_in',
    kind: 'function',
    description: '检查活跃字段在字符串列表',
    example: '|take(method)| chars_in([GET, POST])|',
    insertText: 'chars_in([${...}])',
  },
  {
    label: 'starts_with',
    kind: 'function',
    description: '检查活跃字段以指定前缀开头',
    example: '|take(url)| starts_with("http")|',
    insertText: 'starts_with("${prefix}")',
  },
  {
    label: 'regex_match',
    kind: 'function',
    description: '正则匹配活跃字段',
    example: '|take(message)| regex_match("error")|',
    insertText: 'regex_match("${pattern}")',
  },
  {
    label: 'digit_has',
    kind: 'function',
    description: '检查活跃字段等于数字',
    example: '|take(code)| digit_has(200)|',
    insertText: 'digit_has(${num})',
  },
  {
    label: 'digit_in',
    kind: 'function',
    description: '检查活跃字段在数字列表',
    example: '|take(status)| digit_in([200, 201])|',
    insertText: 'digit_in([${...}])',
  },
  {
    label: 'digit_range',
    kind: 'function',
    description: '检查活跃字段在数字区间',
    example: '|take(status)| digit_range(200, 299)|',
    insertText: 'digit_range(${min}, ${max})',
  },
  {
    label: 'ip_in',
    kind: 'function',
    description: '检查活跃 IP 在列表',
    example: '|take(client_ip)| ip_in([127.0.0.1])|',
    insertText: 'ip_in([${...}])',
  },
  {
    label: 'json_unescape',
    kind: 'function',
    description: 'JSON 反转义',
    example: '|take(message)| json_unescape()|',
    insertText: 'json_unescape()',
  },
  {
    label: 'base64_decode',
    kind: 'function',
    description: 'Base64 解码',
    example: '|take(payload)| base64_decode()|',
    insertText: 'base64_decode()',
  },
  {
    label: 'chars_replace',
    kind: 'function',
    description: '字符串替换',
    example: '|take(message)| chars_replace(error, ok)|',
    insertText: 'chars_replace(${from}, ${to})',
  },
  {
    label: 'not',
    kind: 'function',
    description: '对函数结果取反',
    example: '|not(chars_has(error))|',
    insertText: 'not(${fun_call})',
  },
  // 以下为包含 | 字符的扩展数据
  {
    label: '|',
    kind: 'function',
    description: '自定义预处理扩展',
    example: '|plg_pipe/dayu|',
    insertText: '| plg_pipe/${name}',
  },
  {
    label: '|',
    kind: 'function',
    description: '移除 BOM（字节顺序标记）',
    example: '|strip/bom|',
    insertText: '| strip/bom',
  },
  {
    label: '|',
    kind: 'function',
    description: '选择指定字段为活跃字段',
    example: '|take(name)|',
    insertText: '| take(${name})',
  },
  {
    label: '|',
    kind: 'function',
    description: '选择最后一个字段为活跃字段',
    example: '|last()|',
    insertText: '| last()',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查字段是否存在',
    example: '|f_has(status)|',
    insertText: '| f_has(${name})',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查字段值等于字符串',
    example: '|f_chars_has(status, success)|',
    insertText: '| f_chars_has(${name}, ${val})',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查字段值不等于字符串',
    example: '|f_chars_not_has(level, error)|',
    insertText: '| f_chars_not_has(${name}, ${val})',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查字段值在字符串列表',
    example: '|f_chars_in(method, [GET, POST])|',
    insertText: '| f_chars_in(${name}, [...])',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查字段值等于数字',
    example: '|f_digit_has(code, 200)|',
    insertText: '| f_digit_has(${name}, ${num})',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查字段值在数字列表',
    example: '|f_digit_in(status, [200, 201])|',
    insertText: '| f_digit_in(${name}, [...])',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查 IP 在列表',
    example: '|f_ip_in(client_ip, [127.0.0.1])|',
    insertText: '| f_ip_in(${name}, [...])',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查活跃字段存在',
    example: '|take(name)| has()|',
    insertText: '| has()',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查活跃字段等于字符串',
    example: '|take(status)| chars_has(success)|',
    insertText: '| chars_has(${val})',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查活跃字段不等于字符串',
    example: '|take(level)| chars_not_has(error)|',
    insertText: '| chars_not_has(${val})',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查活跃字段在字符串列表',
    example: '|take(method)| chars_in([GET, POST])|',
    insertText: '| chars_in([${...}])',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查活跃字段以指定前缀开头',
    example: '|take(url)| starts_with("http")|',
    insertText: '| starts_with("${prefix}")',
  },
  {
    label: '|',
    kind: 'function',
    description: '正则匹配活跃字段',
    example: '|take(message)| regex_match("error")|',
    insertText: '| regex_match("${pattern}")',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查活跃字段等于数字',
    example: '|take(code)| digit_has(200)|',
    insertText: '| digit_has(${num})',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查活跃字段在数字列表',
    example: '|take(status)| digit_in([200, 201])|',
    insertText: '| digit_in([${...}])',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查活跃字段在数字区间',
    example: '|take(status)| digit_range(200, 299)|',
    insertText: '| digit_range(${min}, ${max})',
  },
  {
    label: '|',
    kind: 'function',
    description: '检查活跃 IP 在列表',
    example: '|take(client_ip)| ip_in([127.0.0.1])|',
    insertText: '| ip_in([${...}])',
  },
  {
    label: '|',
    kind: 'function',
    description: 'JSON 反转义',
    example: '|take(message)| json_unescape()|',
    insertText: '| json_unescape()',
  },
  {
    label: '|',
    kind: 'function',
    description: 'Base64 解码',
    example: '|take(payload)| base64_decode()|',
    insertText: '| base64_decode()',
  },
  {
    label: '|',
    kind: 'function',
    description: '字符串替换',
    example: '|take(message)| chars_replace(error, ok)|',
    insertText: '| chars_replace(${from}, ${to})',
  },
  {
    label: '|',
    kind: 'function',
    description: '对函数结果取反',
    example: '|not(chars_has(error))|',
    insertText: '| not(${fun_call})',
  },
];

export default WPL_COMPLETION_TABLE;
