version = "1.0"

[generator]
count = 10
speed = 1000
parallel = 1

[output]
connect = "syslog_udp_sink"

[output.params]
addr = "0.0.0.0"
port = 31601
protocol = "udp"

[logging]
level = "warn"
output = "console"

[presets]
