version = "1.0"

[generator]
mode = "rule"
count = 10
speed = 1000
parallel = 1

[output]
connect = "syslog_udp_sink"

[output.params]
addr = "0.0.0.0"
port = 31601
protocol = "udp"

[logging]
level = ""
module_levels = []
output = ""
file_path = "./data/logs"

[presets]
