[[connectors]]
id = "postgres_src"
type = "postgres"
allow_override = ["endpoint", "username", "password","database","table","schema","batch", "cursor_column", "cursor_type", "start_from", "start_from_format"]
[connectors.params]
endpoint = "localhost:5432"
username = "postgres"
password = "123456"
database = "wparse"
table = "nginx_logs"
schema = "public"
batch = 1000
cursor_column = "wp_event_id"
cursor_type = "int"
